version: '3.9'

services:
  postgres:
    image: postgres
    container_name: local_pgdb
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - .env
    volumes:
      - 'local_pgdb:/var/lib/postgresql/data'
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - '5050:80'
    env_file:
      - .env
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  local_pgdb:
  pgadmin-data:
